vim.cmd("hi NormalFloat guibg=none")
vim.cmd("hi! link FloatBorder DiagnosticInfo")
vim.cmd("hi! link NeoTreeFloatTitle DiagnosticInfo")
vim.cmd("hi! VisualIlluminate ctermbg=242 guibg=#323641")
vim.cmd("hi! Visual guibg=#1b3159")
