unbind C-b
set-option -g prefix C-\\
set -g mouse on
set-option -g default-shell /bin/zsh
set-option -g status-interval 1

# for nvim
set -g focus-events on
# for nvim zen-mode
set-option -g allow-passthrough on

# IMPORTANT 
set -g default-terminal "xterm-256color"
set -sa terminal-overrides ',xterm-256color:RGB'
set -as terminal-overrides ',*:Smulx=\E[4::%p1%dm'  # undercurl support
set -as terminal-overrides ',*:Setulc=\E[58::2::%p1%{65536}%/%d::%p1%{256}%/%{255}%&%d::%p1%{255}%&%d%;m'  # underscore colors

bind R source-file ~/.config/tmux/tmux.conf \; display-message "Config File is reloaded! ~/.config/tmux/tmux.conf"

# Pane config options
bind -n M-Up resize-pane -U 2
bind -n M-Down resize-pane -D 2
bind -n M-Right resize-pane -R 5
bind -n M-Left resize-pane -L 5

bind \\ split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"
unbind q
bind q killp
bind Q killw

# Window config options
bind S command-prompt "rename-session '%%'"
bind r command-prompt "rename-window '%%'"
unbind n
bind n new-window
bind -n M-, prev
bind -n M-. next

# Basic config options
set -g base-index 1
set -g renumber-windows on
set -g escape-time 0

# Enable Vi option in copy mode
set-window-option -g mode-keys vi

unbind [
unbind c
bind c copy-mode

bind -T copy-mode-vi 'v' send -X begin-selection
bind -T copy-mode-vi 'V' send -X select-line
bind -T copy-mode-vi 'y' send -X copy-selection

set -g display-time 3000

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'catppuccin/tmux'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'tmux-plygins/tmux-yank'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'omerxx/tmux-floax'

# Session config
set -g @resurrect-capture-pane-contents 'on'
set -g @resurrect-strategy-nvim 'session'

# Floax config
# set -g @floax-bind 't'
# set -g @floax-bind-menu 'p'
# set -g @floax-width '80%'
# set -g @floax-height '80%'
# set -g @floax-border-color 'magenta'
# set -g @floax-text-color 'blue'
# set -g @floax-change-path 'true'

# Tmux Popup config
bind -n M-l popup -d '#{pane_current_path}' -w 90% -h 90% "lazygit"

# Colorscheme config
set -g status-position top

set -g @catppuccin_flavour 'mocha' # latte,frappe, macchiato or mocha
set -g @catppuccin_status_background 'default'

set -g @catppuccin_window_left_separator ""
set -g @catppuccin_window_right_separator " "
set -g @catppuccin_window_middle_separator " █"
set -g @catppuccin_window_number_position "right"

set -g @catppuccin_window_status_enable "yes"
set -g @catppuccin_window_status_icon_enable "yes"
set -g @catppuccin_icon_window_last ""
set -g @catppuccin_icon_window_current "󰖯"
set -g @catppuccin_icon_window_zoom "󰁌"
set -g @catppuccin_icon_window_mark "󰃀"
set -g @catppuccin_icon_window_silent "󰂛"
set -g @catppuccin_icon_window_activity "󱅫"
set -g @catppuccin_icon_window_bell "󰂞"

set -g @catppuccin_window_default_fill "number"
set -g @catppuccin_window_default_background "#1f2029" #323641
set -g @catppuccin_window_default_text "#W"

set -g @catppuccin_window_current_fill "number"
set -g @catppuccin_window_current_background "#323641" #1f2029
set -g @catppuccin_window_current_text "#W"

set -g @catppuccin_status_modules_right "directory user date_time"
set -g @catppuccin_status_modules_left "session"

set -g @catppuccin_date_time_text "%d-%m-%Y"
set -g @catppuccin_status_left_separator  " "
set -g @catppuccin_status_right_separator " "
set -g @catppuccin_status_fill "icon"
set -g @catppuccin_status_connect_separator "no"

set -g @catppuccin_user_color "blue" #7dcfff
set -g @catppuccin_date_time_color "cyan"

set -g @catppuccin_directory_color "magenta" #c577dc
set -g @catppuccin_directory_icon ""
set -g @catppuccin_directory_text "#{b:pane_current_path}"

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
